import { NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { prisma } from "@/lib/prisma";

const anthropic = new Anthropic();

const TONE_PROMPTS: Record<string, string> = {
  casual: "Write like you're texting a close friend — relaxed, natural, no formality. Short sentences, maybe lowercase, no corporate-speak.",
  warm: "Write with genuine warmth and care. Sound like someone who really values this person and is excited to connect.",
  formal: "Write professionally and respectfully. Complete sentences, correct grammar, polite but not stiff.",
  playful: "Write with light humor and energy. Fun, maybe a bit silly, use their interests or shared memories if you know any.",
};

const TYPE_PROMPTS: Record<string, string> = {
  generic: 'This is a general "how are you" style check-in. Ask how they\'re doing, what\'s new, reference something personal if available.',
  "hangout-prompt": "This is a hangout-prompt message — the goal is to actually propose hanging out or making plans. Don\'t just ask how they are; push toward scheduling something.",
};

export async function POST(request: Request) {
  const { checkInId, contactId, tone = "casual", checkInType = "generic", platform } = await request.json();

  if (!contactId) {
    return NextResponse.json({ error: "contactId is required" }, { status: 400 });
  }

  const contact = await prisma.contact.findUnique({
    where: { id: contactId },
    select: { firstName: true, lastName: true, notes: true },
  });

  if (!contact) {
    return NextResponse.json({ error: "Contact not found" }, { status: 404 });
  }

  const name = [contact.firstName, contact.lastName].filter(Boolean).join(" ");
  const toneInstruction = TONE_PROMPTS[tone] ?? TONE_PROMPTS.casual;
  const typeInstruction = TYPE_PROMPTS[checkInType] ?? TYPE_PROMPTS.generic;

  // Fetch recent message history to avoid repetition
  const recentMessages = await prisma.messageLog.findMany({
    where: { contactId },
    orderBy: { createdAt: "desc" },
    take: 5,
    select: { message: true },
  });

  const contextBlock = contact.notes
    ? `\nContext about ${name}: ${contact.notes}`
    : "";

  const recentBlock = recentMessages.length > 0
    ? `\nRecent messages already sent to ${name} (DO NOT repeat these or use similar phrasing):\n${recentMessages.map((m: { message: string }) => `- "${m.message}"`).join("\n")}`
    : "";

  const systemPrompt = `You are generating a check-in text message on behalf of the user. You write from the user's perspective — first person, as if they are sending it themselves.

${toneInstruction}

Rules:
- Maximum 2-3 sentences
- Do NOT include any greeting like "Hey [Name]" — the recipient already knows who's texting
- Do NOT use emojis unless the tone is playful
- Do NOT start with "I" — vary the opening
- Do NOT include a sign-off or signature
- Sound completely human and spontaneous, never like it was generated by AI
- Never use the word "reconnect" or corporate-adjacent words like "touch base", "circle back", "check in" as a phrase${contextBlock}${recentBlock}`;

  const userPrompt = `Write a text message to ${contact.firstName}. ${typeInstruction}`;

  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 200,
    system: systemPrompt,
    messages: [{ role: "user", content: userPrompt }],
  });

  const message = response.content[0].type === "text" ? response.content[0].text.trim() : "";

  // Log as draft
  const log = await prisma.messageLog.create({
    data: {
      contactId,
      checkInId: checkInId ?? null,
      platform: platform ?? "unknown",
      tone,
      message,
      status: "draft",
    },
  });

  return NextResponse.json({ message, logId: log.id });
}
